version: '3.8'

services:
  # debug1:
  #   image: quay.io/kgfathur/rhubi:8.3
  #   command: ping -i 60 8.8.8.8
  #   networks:
  #     - mon_net
  #   deploy:
  #     placement:
  #       constraints: [ node.hostname == $WORKER1 ]
  #     endpoint_mode: dnsrr
  #     mode: "replicated"
  #     replicas: 1
  #     resources:
  #       limits:
  #         memory: 1G

  mariadb1:
    user: "1002:0"
    image: bitnami/mariadb-galera:10.3.28
    volumes:
      - mariadb1:/bitnami/mariadb
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=galera
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb2:4567,0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=backup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD_FILE=/run/secrets/backup_password
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/root_password
      - MARIADB_USER=admin
      - MARIADB_PASSWORD_FILE=/run/secrets/admin_password
      - MARIADB_REPLICATION_USER=replica_user
      - MARIADB_REPLICATION_PASSWORD_FILE=/run/secrets/replica_password
    secrets:
      - root_password
      - admin_password
      - backup_password
      - replica_password
    networks:
      - mon_net
    # ports:
    #   - target: 3306
    #     published: 3306
    #     protocol: tcp
    #     mode: host
    deploy:
      placement:
        constraints: [ node.hostname == $WORKER1 ]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
      resources:
        limits:
          memory: 4G

  mariadb2:
    user: "1002:0"
    image: bitnami/mariadb-galera:10.3.28
    volumes:
      - mariadb2:/bitnami/mariadb
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=galera
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb1:4567,0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=backup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD_FILE=/run/secrets/backup_password
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/root_password
      - MARIADB_USER=admin
      - MARIADB_PASSWORD_FILE=/run/secrets/admin_password
      - MARIADB_REPLICATION_USER=replica_user
      - MARIADB_REPLICATION_PASSWORD_FILE=/run/secrets/replica_password
    secrets:
      - root_password
      - admin_password
      - backup_password
      - replica_password
    networks:
      - mon_net
    # ports:
    #   - target: 3306
    #     published: 3306
    #     protocol: tcp
    #     mode: host
    deploy:
      placement:
        constraints: [ node.hostname == $WORKER2 ]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
      resources:
        limits:
          memory: 4G

secrets:
  root_password:
    external: true
  admin_password:
    external: true
  backup_password:
    external: true
  replica_password:
    external: true

networks:
  mon_net:
    external: true
  macvnet:
    external: true

volumes:
  mariadb1:
    driver: local
    driver_opts:
      type: none
      device: /data/mariadb1
      o: bind
  mariadb2:
    driver: local
    driver_opts:
      type: none
      device: /data/mariadb2
      o: bind
