apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  # imagePullSecrets:
  # - name: pull-secret
  containers:
    - name: nginx
      image: quay.io/kgfathur/nginx-rootless:1.22-ubuntu20.04-fpm
      ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      # imagePullSecrets:
      # - name: pull-secret
      containers:
      - name: nginx
        image: quay.io/kgfathur/nginx-rootless:1.22-ubuntu20.04-fpm
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx