
CREATE USER 'admin'@'%' IDENTIFIED BY 'RANDOM PASSWORD';
SET PASSWORD FOR 'admin'@'%' = '*4C85F';
GRANT ALL PRIVILEGES ON * . * TO 'admin'@'%';
FLUSH PRIVILEGES;

CREATE USER 'admin'@'%' IDENTIFIED BY 'RANDOM PASSWORD';
SET PASSWORD FOR 'admin'@'%' = '*4C85F';
GRANT ALL PRIVILEGES ON * . * TO 'admin'@'%';
FLUSH PRIVILEGES;

CREATE USER 'grafana'@'10.0.0.0/255.0.0.0' IDENTIFIED BY 'RANDOM PASSWORD';
SET PASSWORD FOR 'grafana'@'10.0.0.0/255.0.0.0' = '*13F1D';
-- GRANT ALL PRIVILEGES ON grafana.* TO 'grafana'@'10.0.0.0/255.0.0.0';
-- FLUSH PRIVILEGES;
