version: '3.8'

services:
  webapp1:
    image: php:7.4-apache-buster
    container_name: webapp1
    environment:
      - HOSTNAME=webapp1
      - node_id='webapp1'
    volumes: 
      - ./sample-web:/var/www/html
    ports:
      - 80:80
    network_mode: "host"
    # networks:
    #   - elastic
    healthcheck:
      test: curl -s https://localhost >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 10s
      timeout: 5s
      retries: 5
